CertiPro/urls.py
from django.contrib import admin
from django.urls import include, path
from usuarios import views

urlpatterns = [
    path("", views.usuarioLogin, name='Login'),
    path('admin/', admin.site.urls),
    
    path('usuario/', include('usuarios.urls')),
    path('administradores/', include('administradores.urls')),
]

administradores/urls.py
from django.urls import path
from . import views

app_name = 'administradores'

urlpatterns = [
    path('login/', views.administrador_login, name='administrador_login'),
    # Agrega aquí más URLs para las demás funcionalidades del administrador
    
    path('inicio/<str:usuario>/', views.administrador_inicio, name='administrador_inicio'),  # Asegúrate de tener el mismo nombre aquí
    
    path('actualizacion/', views.actualizacion, name='actualizacion'),
    
    
    path('agregar_pregunta/', views.agregar_pregunta, name='agregar_pregunta'),
    path('editar_pregunta/<int:pk>/', views.editar_pregunta, name='editar_pregunta'),

    path('borrar_pregunta/<int:pk>/', views.borrar_pregunta, name='borrar_pregunta'),
]

administradores/models.py
from django.db import models
from django.contrib.auth.models import User

class Administrador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    actualizacion = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
class Pregunta(models.Model):
    TIPOS_PREGUNTA = (
        ('text', 'Texto'),
        ('number', 'Número'),
        ('radio', 'Opción única (Radio)'),
        ('checkbox', 'Casilla de verificación (Checkbox)'),
        ('color', 'Color'),
        ('date', 'Fecha'),
        ('datetime-local', 'Fecha y hora local'),
        ('email', 'Email'),
        ('file', 'Archivo'),
        ('month', 'Mes'),
        ('range', 'Rango'),
        ('tel', 'Teléfono'),
        ('time', 'Hora'),
        ('url', 'URL'),
        ('week', 'Semana'),
        # Agrega más opciones aquí según tus necesidades
    )

    pregunta = models.CharField(max_length=255)
    tipo = models.CharField(max_length=20, choices=TIPOS_PREGUNTA)

    def __str__(self):
        return self.pregunta

administradores/forms.py
from django import forms
from .models import Pregunta

class PreguntaForm(forms.ModelForm):
    class Meta:
        model = Pregunta
        fields = ['pregunta', 'tipo']

administradores/views.py
from collections import UserDict
from django.contrib.auth import login, authenticate
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from administradores import models
from administradores.models import Administrador
from administradores.models import Pregunta
from .forms import PreguntaForm




def administrador_login(request):
    if request.method == 'POST':
        identificacion = request.POST.get('identificacion')
        password = request.POST.get('password')
        user = authenticate(request, username=identificacion, password=password)

        if user is not None and user.administrador:
            login(request, user)
            return redirect('administradores:administrador_inicio', usuario=user.username)
        else:
            messages.error(request, 'Identificación o contraseña incorrecta.')

    return render(request, "administradores/login.html")


def administrador_inicio(request, usuario):
    usuario = request.user
    
    # Obtener el objeto Administrador asociado al usuario actual
    try:
        administrador = Administrador.objects.get(user=request.user)
    except Administrador.DoesNotExist:
        administrador = None
    
    preguntas = Pregunta.objects.all()
    
    # Obtener los tipos de preguntas disponibles
    tipos_pregunta = Pregunta.TIPOS_PREGUNTA
    
    context = {
            'usuario': usuario, 
            'administrador': administrador,
            'preguntas': preguntas,
            'tipos_pregunta': tipos_pregunta,
            }
    return render(request, "administradores/index.html", context)






@csrf_exempt
def actualizacion(request):
    if request.method == 'POST':
        activada = request.POST.get('activada')
        
        if activada == "on":
            activada = True
        else:
            activada = False
        
        try:
            administrador = Administrador.objects.get(user=request.user)
            administrador.actualizacion = activada
            administrador.save()
            return redirect('administrador_inicio', usuario=request.user.username)
        except Administrador.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'No se encontró el registro del Administrador'}, status=400)

    # Si la solicitud no es POST, retornamos un error
    return JsonResponse({'success': False, 'error': 'Solicitud inválida'}, status=400)

def agregar_pregunta(request):
    form = PreguntaForm()

    if request.method == 'POST':
        form = PreguntaForm(request.POST)
        if form.is_valid():
            pregunta = form.save()
            # Devolver una respuesta JSON con un mensaje de éxito y la pregunta recién agregada
            return JsonResponse({'success': True, 'pregunta': pregunta.pregunta})
        else:
            # Devolver una respuesta JSON con los errores del formulario
            return JsonResponse({'success': False, 'errors': form.errors})
    
    context = {'form': form}
    
    if request.is_ajax():
        return render(request, "administradores/modal_agregar_pregunta.html", context)
    else:
        return render(request, "administradores/index.html", context)

def editar_pregunta(request):
    if request.method == 'POST':
        pregunta_id = request.POST.get('preguntaId')
        pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
        form = PreguntaForm(request.POST, instance=pregunta)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    
    return JsonResponse({'success': False, 'message': 'Método no válido'})

def borrar_pregunta(request, pk):
    pregunta = get_object_or_404(Pregunta, pk=pk)
    if request.method == 'POST':
        pregunta.delete()
        return redirect('administradores:administrador_inicio')
    return render(request, 'administradores/borrar_pregunta_confirm.html', {'pregunta': pregunta})

administradores/templates/administradores/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login - Seguridad Mosgal</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bienvenido - Administrador</h1>
                                    </div>
                                    <form class="user" method="POST" action="{% url 'administradores:administrador_login' %}">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="number" class="form-control form-control-user"
                                                id="id_identificacion" name="identificacion"
                                                aria-describedby="emailHelp" placeholder="Ingrese su identificación">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="id_password" name="password"
                                                placeholder="Contraseña">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="id_customCheck" name="recordarme">
                                                <label class="custom-control-label" for="id_customCheck">Recordarme</label>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Iniciar Sesión
                                        </button>
                                    </form>
                                    {% if messages %}
                                        <div class="text-center">
                                            {% for message in messages %}
                                                <p class="text-danger">{{ message }}</p>
                                            {% endfor %}
                                        </div>
                                    {% endif %}                           
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Recuperar contraseña</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>